---
- hosts: localhost 
  gather_facts: no
  module_defaults:
    group/aws:
      region: "us-east-2"
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: Module5
        cidr_block: 10.10.0.0/16
        tags:
          Module: 5
        state: present 
      register: vpc
    - name: debug
      debug: var=vpc
    - name: Create public subnet
       ec2_vpc_subnet:
         vpc_id: "{{ vpc.vpc.id }}"
         tags: 
           Name: Module5 public
           mODule: 5
          cidr: 10.10.0.0/24
          state: present 
    - name: Create private subnet
       ec2_vpc_subnet:
         vpc_id: "{{ vpc.vpc.id }}"
         tags: 
           Name: Module5 private
           Module: 5
          cidr: 10.10.1.0/24
          state: present 
     - name: Create internet gateway
       ec2__vpc_igw:
         vpc_id: "{{ vpc.vpc.id }}"
