---
- hosts: al2
  become: yes
  vars: 
    index_file: developer/var/www/html/index.html
  tasks: 
    - name: Install emacs-nox
      package: 
        name: emacs-nox
        state: present
        update_cache: yes
    - name: Install nano
        package:
          name: nano
          state: present
    - name: Install apache
        package: 
          name: httpd
          state: present
    - name: Copy index.html
      copy: 
        src: "{{ index_file }}"
        dest: /var/www/html/index.html
        owner: apache
        group: apache
    - name: Start apache
      service: 
        name: httpd
        state: started
        enabled: true   
