---
- hosts: localhost
  gather_facts: no
  vars: 
    ami_id: "ami-09d95fab7fff3776c"
  module_defaults:
    group/aws: 
      region: "us-east-2"
  tasks: 
    - name: Make Module5 EC2 Instances
      ec2: 
        key_name: m5ec2
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags: 
          Name: Module5createEC2ONE
          Module: 5
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        exact_count: 1
        count_tag: 
          Name: Module5createEC2 
          Module: 5
